#! /usr/bin/env python3
#
# csv2img.py
# A utility script to take a csv file generated by the barricelli54 program
# and generate an image in the style used in Barricelli's 1954 paper.
#
# usage:
# > ./csv2img.py [-b] [-f <png|pdf|svg>] <input_csv_file> [label_specs...]
# where the optional -b flag specifies that grid lines are to be drawn,
# -f selects the output format (default: pdf), and
# label_specs are of the form: <above|below>:<start_col>:<end_col>:<label_text>
#
# Program written by ChatGPT and Tim Taylor
# July 2025

import csv
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import sys
import os
import matplotlib.patheffects as path_effects


def read_csv_to_array(file_path):
    """Reads a CSV file of numerical values or 'x' into a 2D list."""
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        data = []
        for row in reader:
            processed_row = []
            for item in row:
                item = item.strip().lower()
                if item == 'x':
                    processed_row.append('x')
                else:
                    try:
                        processed_row.append(int(item))
                    except ValueError:
                        processed_row.append(0)
            data.append(processed_row)
    return data

def measure_digit_bottom_offset(fig, ax):
    """Measures how far above the bottom boundary of a (unit-height) cell
    the bottom of a rendered digit sits, using a representative digit.

    get_window_extent() alone cannot be used for this: it pads a text's
    bounding box with the font's generic descent region, which digits --
    having no descenders -- never actually render into, so the resulting
    offset would be much smaller than the digit's true visible extent.
    Instead the digit is rendered and its actual ink pixels are inspected.
    """
    dummy = ax.text(0.5, 0.5, "0", ha='center', va='center', fontsize=6, fontweight='bold')
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    bbox = dummy.get_window_extent(renderer=renderer)

    buf = np.asarray(fig.canvas.buffer_rgba())
    fig_height_px = buf.shape[0]
    row_top = max(int(fig_height_px - bbox.y1) - 3, 0)
    row_bottom = int(fig_height_px - bbox.y0) + 3
    col_left = max(int(bbox.x0) - 3, 0)
    col_right = int(bbox.x1) + 3
    region = buf[row_top:row_bottom, col_left:col_right, :3]
    ink_rows = np.where((region.min(axis=2) < 128).any(axis=1))[0]
    ink_bottom_row = ink_rows.max() + row_top

    ink_bottom_data_y = ax.transData.inverted().transform((bbox.x0, fig_height_px - ink_bottom_row))[1]
    dummy.remove()
    return 1 - ink_bottom_data_y

def draw_bracket(ax, start, end, row_y, above=True, label=""):
    """Draw a simple horizontal bracket line with caps and a label above or below."""
    mid = (start + end) / 2
    label_y = row_y + (-0.45 if above else 0.45)
    cap_height = 0.15 if above else -0.15

    # Straight horizontal line
    ax.plot([start, end], [row_y, row_y], color='black', linewidth=0.8)

    # Caps at each end
    ax.plot([start, start], [row_y, row_y + cap_height], color='black', linewidth=0.8)
    ax.plot([end, end], [row_y, row_y + cap_height], color='black', linewidth=0.8)

    # Label
    ax.text(mid, label_y, label, ha='center', va='center', fontsize=6, fontweight='bold')

def draw_grid(data, output_path, draw_borders=False, labels=[]):
    rows = len(data)
    cols = len(data[0]) if rows > 0 else 0
    fig_height = rows * 0.125 + (0.4 if len(labels) > 0 else 0.0)
    fig, ax = plt.subplots(figsize=(cols * 0.125, fig_height), dpi=300)

    # set margins around the fig (larger margins if there are labels to be displayed)
    ax.set_xlim(-0.25, cols + 0.25)
    if len(labels) == 0:
        ax.set_ylim(-0.25, rows + 0.25)
    else:
        ax.set_ylim(-1.25, rows + 1.25)

    ax.axis('off')
    ax.invert_yaxis()

    # fix the axes position now so that pixel<->data coordinate mapping used
    # below for measuring the digit's extent matches what will end up in the
    # saved image (subplots_adjust must not change after that measurement)
    plt.subplots_adjust(left=0, right=1, top=1, bottom=0)
    fig.canvas.draw()

    # every negative number's bar is placed at the same fixed height above
    # its own cell's bottom boundary, halfway to the bottom of the digit
    bar_height_above_cell_bottom = measure_digit_bottom_offset(fig, ax) / 2

    for y in range(rows):
        for x in range(cols):
            value = data[y][x]

            if draw_borders:
                rect = patches.Rectangle((x, y), 1, 1, linewidth=0.25, edgecolor='black', facecolor='none')
                ax.add_patch(rect)

            if value == 0:
                continue

            if value == 'x':
                display_text = 'x'
                ax.text(x + 0.5, y + 0.5, display_text,
                        ha='center', va='center', fontsize=6, fontweight='bold', clip_on=True)
            elif value < 0:
                num_str = str(abs(int(value)))
                ax.text(x + 0.5, y + 0.5, num_str,
                        ha='center', va='center', fontsize=6, fontweight='bold', clip_on=True)
                text_width = 0.4 * len(num_str)
                bar_y = (y + 1) - bar_height_above_cell_bottom
                ax.plot([x + 0.5 - text_width / 2, x + 0.5 + text_width / 2], [bar_y, bar_y],
                        linewidth=1, color='black')
            else:
                display_text = str(int(value))
                ax.text(x + 0.5, y + 0.5, display_text,
                        ha='center', va='center', fontsize=6, fontweight='bold', clip_on=True)

    for label in labels:
        position, start, end, text = label
        start, end = int(start), int(end)
        if position == 'above':
            draw_bracket(ax, start, end, -0.2, above=True, label=text)
        elif position == 'below':
            draw_bracket(ax, start, end, rows + 0.35, above=False, label=text)

    plt.savefig(output_path, bbox_inches='tight', pad_inches=0)
    plt.close()

VALID_FORMATS = ('pdf', 'png', 'svg')

def print_usage_and_exit():
    print("Usage: csv2img.py [-b] [-f <png|pdf|svg>] <input_csv_file> [label_specs...]")
    print("label_specs format: above|below:<start_col>:<end_col>:<label_text>")
    sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print_usage_and_exit()

    draw_borders = False
    output_format = 'pdf'
    arg_index = 1
    while arg_index < len(sys.argv) and sys.argv[arg_index].startswith('-'):
        if sys.argv[arg_index] == '-b':
            draw_borders = True
            arg_index += 1
        elif sys.argv[arg_index] == '-f':
            if arg_index + 1 >= len(sys.argv):
                print_usage_and_exit()
            output_format = sys.argv[arg_index + 1].lower()
            if output_format not in VALID_FORMATS:
                print(f"Invalid format: {output_format} (must be one of {', '.join(VALID_FORMATS)})")
                print_usage_and_exit()
            arg_index += 2
        else:
            print_usage_and_exit()

    if arg_index >= len(sys.argv):
        print_usage_and_exit()

    input_csv = sys.argv[arg_index]
    arg_index += 1
    label_specs = sys.argv[arg_index:]

    if not os.path.isfile(input_csv):
        print(f"Error: input CSV file not found: {input_csv}")
        sys.exit(1)

    labels = []
    for spec in label_specs:
        try:
            position, start, end, text = spec.split(':', 3)
            if position not in ('above', 'below'):
                raise ValueError
            labels.append((position, start, end, text))
        except ValueError:
            print(f"Invalid label specification: {spec}")
            print_usage_and_exit()

    output_image = os.path.splitext(os.path.basename(input_csv))[0] + "." + output_format

    data = read_csv_to_array(input_csv)
    draw_grid(data, output_image, draw_borders, labels)

    print(f"Image saved as {output_image}")
